builds:
  - skip: true

checksum:
  name_template: '{{ .ProjectName }}_sha256_checksums.txt'
  algorithm: sha256
  extra_files:
    - glob: ./release/*.dmg
    - glob: ./release/*.exe
    - glob: ./release/*.rpm
    - glob: ./release/*.deb
    - glob: ./release/*.AppImage
    - glob: ./release/*.blockmap
    - glob: ./release/latest*.yml
release:
  # Same as for github
  # Note: it can only be one: either github, gitlab or gitea
  github:
    owner: gavintan
    name: wfrpc_gui

  draft: false

  # You can add extra pre-existing files to the release.
  # The filename on the release will be the last part of the path (base). If
  # another file with the same name exists, the latest one found will be used.
  # Defaults to empty.
  extra_files:
    - glob: ./release/*.dmg
    - glob: ./release/*.exe
    - glob: ./release/*.rpm
    - glob: ./release/*.deb
    - glob: ./release/*.AppImage
    - glob: ./release/*.blockmap
    - glob: ./release/latest*.yml
