name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: install rpm
        if: runner.os == 'macOS'
        run: |
          rpmbuild --version || wget -q https://raw.githubusercontent.com/GavinTan/files/master/picgo/rpm.rb && brew install -q rpm.rb
          rm -rf rpm.rb

      - name: yarn install
        run: yarn

      - name: build
        run: yarn release && yarn release:arm64

      - run: mv dist release

      - name: Create Tag
        run: |
          version=v`node -p "require('./package.json').version"`
          if [ ! $(git tag -l $version) ]; then
            git tag $version
            git push origin $version
          fi

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
